version: '3.10'

services:
  web: &python
    build: .
    env_file:
      - .env.dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
      - celery_worker
  db:
    image: postgres:13
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3.11.1-alpine
  celery_worker:
    build: .
    env_file: .env.dev
    volumes:
      - ./:/usr/src/app
    entrypoint: celery -A core worker -l info
    depends_on:
      - rabbitmq
      - db
