# Generated by Django 4.1.2 on 2022-10-10 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="page",
            name="follow_requests",
            field=models.ManyToManyField(
                blank=True, related_name="requests", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="follows", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
