# Generated by Django 4.1.2 on 2022-10-11 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0003_alter_post_options_alter_page_follow_requests_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
