# Generated by Django 4.1.2 on 2022-10-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_post_like_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like_count",
        ),
    ]
